@extends('layouts.app', ['title' => 'Admin | WriteAnything'])
@section('content')
{{-- Dashboard admin adalah pusat statistik, ranking, moderasi, laporan, pinned card, dan manajemen user. --}}
<main class="mx-auto max-w-6xl px-6 pb-24 pt-10 lg:px-10">
    <div class="mb-10"><p class="mb-3 text-xs font-bold uppercase tracking-[.2em] text-[#db9275]">control room</p><h1 class="display text-5xl">admin dashboard.</h1><p class="mt-3 text-sm text-black/55">Pantau aktivitas dan jaga ruang ini tetap aman.</p></div>

    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div class="bg-[#d9d5f2] p-6"><p class="text-xs uppercase tracking-wider text-black/50">jumlah pengguna</p><p class="display mt-3 text-4xl">{{ $stats['users'] }}</p></div>
        <div class="bg-[#f8dda0] p-6"><p class="text-xs uppercase tracking-wider text-black/50">pengguna hari ini</p><p class="display mt-3 text-4xl">{{ $stats['today'] }}</p></div>
        <div class="bg-[#cfe2d4] p-6"><p class="text-xs uppercase tracking-wider text-black/50">catatan dikirim</p><p class="display mt-3 text-4xl">{{ $stats['cards'] }}</p></div>
        <div class="bg-[#f3cec2] p-6"><p class="text-xs uppercase tracking-wider text-black/50">menunggu review</p><p class="display mt-3 text-4xl">{{ $stats['pending'] }}</p></div>
    </div>

    <section class="mt-16"><div class="mb-6"><p class="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#db9275]">community pulse</p><h2 class="display text-3xl">pengguna paling aktif.</h2></div><div class="overflow-x-auto border border-black/10 bg-white/40"><table class="w-full min-w-[620px] text-left text-sm"><thead class="border-b border-black/10 text-xs uppercase tracking-wider text-black/45"><tr><th class="p-4">peringkat</th><th class="p-4">pengguna</th><th class="p-4">jumlah catatan</th><th class="p-4">status</th></tr></thead><tbody>@forelse($ranking as $position => $user)<tr class="border-b border-black/10 last:border-0"><td class="p-4 font-semibold">{{ $position + 1 }}</td><td class="p-4 font-semibold">{{ $user->name }} <span class="font-normal text-black/40">@{{ $user->username }}</span></td><td class="p-4"><span class="rounded-full bg-[#d9d5f2] px-3 py-1 font-semibold">{{ $user->cards_count }} catatan</span></td><td class="p-4 text-black/50">{{ $user->is_banned ? 'dibanned' : 'aktif' }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-black/45">Belum ada data pengguna.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-16"><div class="mb-6 flex items-end justify-between"><div><p class="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#db9275]">content desk</p><h2 class="display text-3xl">moderasi catatan.</h2></div><span class="text-sm text-black/45">{{ $stats['pending'] }} pending</span></div><div class="overflow-x-auto border border-black/10 bg-white/40"><table class="w-full min-w-[900px] text-left text-sm"><thead class="border-b border-black/10 text-xs uppercase tracking-wider text-black/45"><tr><th class="p-4">pesan</th><th class="p-4">pengguna</th><th class="p-4">status</th><th class="p-4">aksi</th></tr></thead><tbody>@forelse($cards as $card)<tr class="border-b border-black/10 align-top last:border-0"><td class="max-w-sm p-4 font-medium">{{ Str::limit($card->message, 70) }}<div class="mt-1 text-xs font-normal text-black/40">{{ $card->time_caption }} · {{ $card->signature }}</div></td><td class="p-4 text-black/55">{{ $card->user->username }}</td><td class="p-4"><span class="rounded-full bg-black/5 px-3 py-1 text-xs">{{ $card->status }}</span></td><td class="p-4"><div class="flex flex-wrap gap-3">@if($card->status !== 'approved')<form method="POST" action="{{ route('admin.cards.moderate', [$card, 'approved']) }}">@csrf @method('PATCH')<button class="font-semibold text-[#5d8067]">setujui</button></form>@endif @if($card->status !== 'rejected')<form method="POST" action="{{ route('admin.cards.moderate', [$card, 'rejected']) }}">@csrf @method('PATCH')<button class="font-semibold text-[#a45f4d]">tolak</button></form>@endif<a href="{{ route('admin.cards.edit', $card) }}" class="font-semibold underline">edit</a><form method="POST" action="{{ route('admin.cards.destroy', $card) }}">@csrf @method('DELETE')<button class="font-semibold text-[#a45f4d] underline">hapus</button></form></div></td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-black/45">Belum ada catatan untuk dimoderasi.</td></tr>@endforelse</tbody></table></div></section>
    <section class="mt-16"><div class="mb-6 flex items-end justify-between"><div><p class="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#db9275]">trust & safety</p><h2 class="display text-3xl">laporan masuk.</h2></div><span class="text-sm text-black/45">{{ $stats['reports'] }} laporan</span></div><div class="overflow-x-auto border border-black/10 bg-white/40"><table class="w-full min-w-[760px] text-left text-sm"><thead class="border-b border-black/10 text-xs uppercase tracking-wider text-black/45"><tr><th class="p-4">catatan</th><th class="p-4">alasan</th><th class="p-4">aksi</th></tr></thead><tbody>@forelse($reports as $report)<tr class="border-b border-black/10 last:border-0"><td class="p-4">{{ Str::limit($report->card->message, 70) }}</td><td class="p-4 text-black/55">{{ $report->reason }}</td><td class="p-4"><form method="POST" action="{{ route('admin.reports.resolve', $report) }}">@csrf @method('PATCH')<button class="font-semibold underline">tandai selesai</button></form></td></tr>@empty<tr><td colspan="3" class="p-8 text-center text-black/45">Belum ada laporan baru.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-16"><div class="mb-6"><p class="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#db9275]">announcement desk</p><h2 class="display text-3xl">pinned cards.</h2><p class="mt-2 text-sm text-black/50">Pasang catatan yang ingin selalu muncul di bagian atas wall publik.</p></div><div class="grid gap-4 md:grid-cols-3">@foreach($cards->where('status', 'approved')->take(6) as $card)<div class="flex items-center justify-between border border-black/10 bg-white/40 p-4"><p class="max-w-[70%] text-sm">{{ Str::limit($card->message, 45) }}</p><form method="POST" action="{{ route('admin.cards.pin', $card) }}">@csrf @method('PATCH')<button class="text-xs font-semibold underline">{{ $card->is_pinned ? 'lepas pin' : 'pin card' }}</button></form></div>@endforeach</div></section>

    <section class="mt-16"><div class="mb-6"><p class="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#db9275]">people</p><h2 class="display text-3xl">manajemen pengguna.</h2></div><div class="overflow-x-auto border border-black/10 bg-white/40"><table class="w-full min-w-[850px] text-left text-sm"><thead class="border-b border-black/10 text-xs uppercase tracking-wider text-black/45"><tr><th class="p-4">user</th><th class="p-4">email</th><th class="p-4">terdaftar</th><th class="p-4">status</th><th class="p-4">aksi</th></tr></thead><tbody>@foreach($users as $user)<tr class="border-b border-black/10 last:border-0"><td class="p-4 font-semibold">{{ $user->name }} <span class="font-normal text-black/40">@{{ $user->username }}</span></td><td class="p-4 text-black/55">{{ $user->email }}</td><td class="p-4 text-black/55">{{ $user->created_at->format('d M Y') }}</td><td class="p-4">{{ $user->is_banned ? 'banned permanen' : $user->role }}</td><td class="p-4"><div class="flex gap-3">@if(!$user->is(auth()->user()))<form method="POST" action="{{ route('admin.users.toggle-ban', $user) }}">@csrf @method('PATCH')<button class="underline">{{ $user->is_banned ? 'buka blokir' : 'ban tanpa batas' }}</button></form><form method="POST" action="{{ route('admin.users.destroy', $user) }}">@csrf @method('DELETE')<button class="text-[#a45f4d] underline">hapus</button></form>@endif</div></td></tr>@endforeach</tbody></table></div></section>
</main>
@endsection
